### PR TITLE
fix issue of input test color

### PR DESCRIPTION
**Pull request by Sujeet282000**

### CODE REVIEW

**Comment by Sujeet282000** [comment]
solved

**Comment by Haimantika** [comment]
Hi @Sujeet282000 I have already made a fix for it. Would you like to work on some other improvements? I am making the issues open right now.

**Comment by Sujeet282000** [comment]
Hi @Haimantika  It's great to hear that you've made a fix for the issue.  Currently I'm new to open source, and in learning phase but I'm eager to contribute and learn. I will try my best to to work on some other improvements.

**Comment by Haimantika** [comment]
> Hi @Haimantika It's great to hear that you've made a fix for the issue. Currently I'm new to open source, and in learning phase but I'm eager to contribute and learn. I will try my best to to work on some other improvements.

I have added two issues here, do you want to work on any of these? https://github.com/Haimantika/qrcode-generator/issues

**Comment by Sujeet282000** [comment]
I will definitely look at it

**Comment by Sujeet282000** [comment]
I solved this issue you can check it, Fixes https://github.com/Haimantika/qrcode-generator/issues/5

**Pull request closed without merging**
