### PR TITLE
fix the issue of disable-generate-QR-button

### LINKED ISSUE #5: Disable Generate QR button
If there is no value in the input box, you can disable the Generate QR button.

### PR DESCRIPTION
**Pull request by Sujeet282000**
the issue is,  If there is no value in the input box, you can disable the Generate QR button.

Related Issue
Fixes https://github.com/Haimantika/qrcode-generator/issues/5

### CODE REVIEW

**Comment by Haimantika** [comment]
Hi @Sujeet282000 I tried it locally and it does not disable the button for me. Can you add a screenshot or a screen recording?

**Comment by Sujeet282000** [comment]
https://github.com/Haimantika/qrcode-generator/assets/105284440/be3a787a-b3c6-4c63-8fbb-ce170ba88820

**Comment by Sujeet282000** [comment]
You can see the vedio how it works

**Comment by Haimantika** [comment]
> You can see the vedio how it works

Hi, I guess it will be nice to have the button colour in grey. Also, it does not reflect the latest change where one needs to add a valid URL to generate QR code. Can you do a `git pull` first to have the latest version?

**Comment by Haimantika** [comment]
And the branch also has conflicts, please resolve them :)

**Pull request closed without merging**
